apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitweb
  namespace: my-git
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitweb
  template:
    metadata:
      labels:
        app: gitweb
    spec:
      containers:
        - name: gitweb
          image: madandhungel/my-git
          ports:
            - containerPort: 5000