apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitweb-ingress
  namespace: web-git
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: git.web.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitweb
            port:
              number: 5000